"""
guardrails.py
-------------
Implements pre-execution and post-execution guardrails for safety and policy compliance:
1. Input Sanitization: Detects and rejects prompt injection attempts.
2. Output Compliance: Blocks clinical suggestions, medical diagnosis, or medicine prescriptions,
   routing the caller to standard clinical care instead.
"""

import re
from typing import Dict, Any, Tuple
from src.utils.logger import custom_logger as logger

# Standard compliance warning when medical boundaries are breached
REFUSAL_MESSAGE = (
    "I am an AI assistant and cannot provide medical diagnoses or prescribe medicines. "
    "Please consult a qualified healthcare professional or visit our emergency department "
    "for clinical assistance."
)

PROMPT_INJECTION_PATTERNS = [
    r"ignore\s+(?:all\s+)?prior\s+instructions",
    r"you\s+are\s+now\s+a\s+doctor",
    r"system\s+override",
    r"bypass\s+safety",
    r"disregard\s+instructions"
]

CLINICAL_KEYWORDS = [
    r"\bdiagnose\b",
    r"\bprescription\b",
    r"\bprescribe\b",
    r"\btablets\b",
    r"\bmedicine\b",
    r"\bmedication\b",
    r"\bcure\b",
    r"\bdose\b",
    r"\bdosage\b",
    r"\bantibiotic\b",
    r"\bparacetamol\b",
    r"\bibuprofen\b"
]

class AshaGuardrails:
    """
    Enforces HIPAA-compliant boundary checks and conversation safety.
    """
    @staticmethod
    def inspect_input(user_query: str) -> Tuple[bool, str]:
        """
        Scans incoming transcripts for potential prompt injection attempts.
        Returns:
            (is_safe, filtered_query_or_error_msg)
        """
        query_clean = user_query.strip()
        query_lower = query_clean.lower()
        
        for pattern in PROMPT_INJECTION_PATTERNS:
            if re.search(pattern, query_lower):
                logger.warning(f"Guardrail Flagged: Potential prompt injection attempt detected in query: '{user_query}'")
                return False, "I cannot process that request. Let's keep our conversation centered on hospital information and appointment scheduling."
                
        return True, query_clean

    @staticmethod
    def inspect_output(assistant_response: str) -> str:
        """
        Scans outgoing response generated by any agent for clinical claims, 
        medical advice, or prescriptions.
        Returns:
            The safe response or the standard refusal message.
        """
        response_lower = assistant_response.lower()
        
        for kw in CLINICAL_KEYWORDS:
            if re.search(kw, response_lower):
                # Check if it's booking/scheduling context before refusing
                # E.g. "We need to check your medication status" vs. "Take this medication twice daily"
                # To be completely safe and avoid any liability, we enforce strict refusal if it sounds diagnostic.
                logger.warning(f"Guardrail Flagged: Clinical keyword '{kw}' found in generated response.")
                return REFUSAL_MESSAGE
                
        return assistant_response
